lychee Bracken.wiki > Bracken.wikilog 2>&1
lychee BRCA-diagnostic.wiki > BRCA-diagnostic.wikilog 2>&1
lychee centrifuge.wiki > centrifuge.wikilog 2>&1
lychee choosing-a-metagenomics-classifier.wiki > choosing-a-metagenomics-classifier.wikilog 2>&1
lychee diamund.wiki > diamund.wikilog 2>&1
lychee dive.wiki > dive.wikilog 2>&1
lychee EASTR.wiki > EASTR.wikilog 2>&1
lychee edge-pro.wiki > edge-pro.wikilog 2>&1
lychee elph.wiki > elph.wikilog 2>&1
lychee flash.wiki > flash.wikilog 2>&1
lychee fqtrim.wiki > fqtrim.wikilog 2>&1
lychee genesplicer.wiki > genesplicer.wikilog 2>&1
lychee gffcompare.wiki > gffcompare.wikilog 2>&1
lychee gffread.wiki > gffread.wikilog 2>&1
lychee glimmerhmm.wiki > glimmerhmm.wikilog 2>&1
lychee glimmerm.wiki > glimmerm.wikilog 2>&1
lychee glimmer.wiki > glimmer.wikilog 2>&1
lychee hisat2.wiki > hisat2.wikilog 2>&1
lychee jigsaw.wiki > jigsaw.wikilog 2>&1
lychee kraken2.wiki > kraken2.wikilog 2>&1
lychee krakentools.wiki > krakentools.wikilog 2>&1
lychee kraken.wiki > kraken.wikilog 2>&1
lychee pavian.wiki > pavian.wikilog 2>&1
lychee phymmbl.wiki > phymmbl.wikilog 2>&1
lychee Quake.wiki > Quake.wikilog 2>&1
lychee stringtie.wiki > stringtie.wikilog 2>&1
lychee tophat.wiki > tophat.wikilog 2>&1
