s|https://ccb.jhu.edu/software/kraken2/|https://github.com/DerrickWood/kraken2/wiki|
s|https://ccb.jhu.edu/software/bracken/|https://github.com/jenniferlu717/Bracken/wiki|
s|https://ccb.jhu.edu/software/stringtie/|https://github.com/gpertea/stringtie/wiki|
s|https://ccb.jhu.edu/software/hisat/|https://github.com/DaehwanKimLab/hisat2/wiki|
s|https://ccb.jhu.edu/software/centrifuge/|https://github.com/infphilo/centrifuge/wiki|
s|https://ccb.jhu.edu/software/krakentools/|https://github.com/jenniferlu717/KrakenTools/wiki|
s|https://ccb.jhu.edu/software/pavian/|https://github.com/fbreitwieser/pavian/wiki|
s|https://ccb.jhu.edu/software/kraken/|https://github.com/DerrickWood/kraken/wiki|
s|https://ccb.jhu.edu/software/glimmer/|https://github.com/gmes-glimmer/glimmer3/wiki|
s|https://ccb.jhu.edu/software/glimmerhmm/|https://github.com/yandell-lab/GlimmerHMM/wiki|
s|https://ccb.jhu.edu/software/FLASH/|https://github.com/dstreett/FLASH/wiki|
s|https://ccb.jhu.edu/software/tophat/|https://github.com/cole-trapnell-lab/tophat/wiki|
s|https://ccb.jhu.edu/software/quake/|https://github.com/edwardsLab/Quake/wiki|
s|https://ccb.jhu.edu/software/BRCA-diagnostic/|https://github.com/salzberg-lab/BRCA-diagnostic/wiki|
s|https://ccb.jhu.edu/software/jigsaw/|https://github.com/gpertea/jigsaw/wiki|
s|https://ccb.jhu.edu/software/diamund/|https://github.com/mdozmorov/DIAMUND/wiki|
