s|https://github.com/dpuiu/krakentools|https://github.com/jenniferlu717/KrakenTools|g
s|https://github.com/dpuiu/KrakenTools|https://github.com/jenniferlu717/KrakenTools|g
s|https://github.com/dpuiu/kraken|https://github.com/DerrickWood/kraken|g
s|https://github.com/dpuiu/Bracken|https://github.com/jenniferlu717/Bracken|g
s|https://github.com/dpuiu/stringtie|https://github.com/gpertea/stringtie|g
s|https://github.com/dpuiu/hisat2|https://github.com/DaehwanKimLab/hisat2|g
s|https://github.com/dpuiu/centrifuge|https://github.com/DaehwanKimLab/centrifuge|g
s|https://github.com/dpuiu/pavian|https://github.com/fbreitwieser/pavian|g
s|https://github.com/dpuiu/glimmer|https://github.com/mpertea/glimmer|g
s|https://github.com/dpuiu/flash|https://github.com/TMAGOC/flash|g
s|https://github.com/dpuiu/tophat|https://github.com/cole-trapnell-lab/tophat|g
s|https://github.com/dpuiu/Quake|https://github.com/davek44/Quake|g
s|https://github.com/dpuiu/BRCA-diagnostic|https://github.com/mpertea/BRCA-diagnostic|g
s|https://github.com/dpuiu/jigsaw|https://github.com/gpertea/jigsaw|g
s|https://github.com/dpuiu/gffcompare/|https://github.com/gpertea/gffcompare|g
s|https://github.com/dpuiu/gffread/|https://github.com/gpertea/gffread|g
s|https://github.com/dpuiu/choosing-a-metagenomics-classifier|https://github.com/jenniferlu717/choosing-a-metagenomics-classifier|g
s|https://github.com/dpuiu/EASTR|https://github.com/ishinder/EASTR|g
s|https://github.com/dpuiu/fqtrim|https://ccb.jhu.edu/software/fqtrim|g
s|https://github.com/dpuiu/phymmbl|https://github.com/abradyGDIT/phymmbl|g
s|https://github.com/dpuiu/genesplicer|https://github.com/mpertea/genesplicer|g
s|https://github.com/dpuiu/edge-pro|https://github.com/TMAGOC/edge-pro|g
s|https://github.com/dpuiu/elph|https://github.com/mpertea/elph|g
s|https://github.com/dpuiu/dive|https://github.com/mpertea/dive/wiki|g
s|https://github.com/dpuiu/diamund|https://github.com/mpertea/diamund/wiki|g
