name: Build and Deploy Sphinx

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -r requirements.txt || true

      - name: Generate People Pages
        run: |
          check-jsonschema --schemafile _people/people.schema.json _people/faculty.yaml
          check-jsonschema --schemafile _people/people.schema.json _people/students.yaml
          check-jsonschema --schemafile _people/people.schema.json _people/alumni.yaml
          check-jsonschema --schemafile _people/people.schema.json _people/collaborators.yaml
          check-jsonschema --schemafile _people/people.schema.json _people/postdocs.yaml
          check-jsonschema --schemafile _people/people.schema.json _people/staff.yaml
          jinja2 _templates/people.jinja _people/faculty.yaml       -D title="Faculty"  > people/faculty.md
          jinja2 _templates/people.jinja _people/students.yaml      -D title="Students" > people/students.md
          jinja2 _templates/people.jinja _people/alumni.yaml        -D title="Alumni" > people/alumni.md
          jinja2 _templates/people.jinja _people/collaborators.yaml -D title="Collaborators" > people/collaborators.md
          jinja2 _templates/people.jinja _people/postdocs.yaml      -D title="Postdocs" > people/postdocs.md
          jinja2 _templates/people.jinja _people/staff.yaml         -D title="Staff" > people/staff.md

      - name: Fix GitHub Pages image paths
        run: |
          sed -i 's|img src="/_static/|img src="/www.ccb.jhu.edu/_static/|g' index.md examples/index.md

      - name: Build Sphinx site
        run: |
          make html html_theme=pydata_sphinx_theme
          cp -a _build/pydata_sphinx_theme/. docs/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
